[package]
name = "csvsql"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.1"             # For reading and processing CSV files
sqlparser = "0.12"      # For SQL-like parsing, if you want to leverage an existing parser
